"use client";
import { useMemo, useState, type DragEvent, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { AlertCircle, CheckCircle2, Download, FileSpreadsheet, GripVertical, LoaderCircle, MailCheck, Pencil, Plus, Save, Trash2, UploadCloud, UsersRound, X } from "lucide-react";
import type { EventRecord, RegistrationRecord, RegistrationStatus } from "@/lib/types";
import { formatDateTime } from "@/lib/format";

type Editor = { type:"new"; defaultStatus?:RegistrationStatus } | { type:"edit"; registration:RegistrationRecord } | null;
const statusLabels:Record<RegistrationStatus,string>={confirmed:"已確認",waitlist:"候補",cancelled:"已取消"};
export function AdminRegistrationManager({event,initialRegistrations}:{event:EventRecord;initialRegistrations:RegistrationRecord[]}){
 const router=useRouter(); const [registrations,setRegistrations]=useState(initialRegistrations); const [editor,setEditor]=useState<Editor>(null); const [error,setError]=useState(""); const [saving,setSaving]=useState(false); const [dragId,setDragId]=useState<string|null>(null); const [showImport,setShowImport]=useState(false); const [importing,setImporting]=useState(false); const [importResult,setImportResult]=useState<{importedCount:number;failedCount:number;emailsSent:number;failures:string[]}|null>(null);
 const sessions=useMemo(()=>[...(event.sessions||[])].sort((a,b)=>a.start_at.localeCompare(b.start_at)),[event.sessions]);
 const confirmedGroups=useMemo(()=>event.is_multi_session?sessions.map(s=>({session:s,items:registrations.filter(r=>r.session_id===s.id&&r.status!=="waitlist")})):[{session:null,items:registrations.filter(r=>r.status!=="waitlist")}],[event.is_multi_session,sessions,registrations]);
 const waitlistGroups=useMemo(()=>event.is_multi_session?sessions.map(s=>({session:s,items:registrations.filter(r=>r.session_id===s.id&&r.status==="waitlist")})).filter(g=>g.items.length>0):[{session:null,items:registrations.filter(r=>r.status==="waitlist")}],[event.is_multi_session,sessions,registrations]);
 const waitlistCount=registrations.filter(r=>r.status==="waitlist").length;
 async function savePayload(endpoint:string,method:string,payload:unknown){const response=await fetch(endpoint,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||"未能儲存參加者");return result as RegistrationRecord;}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editor)return;setSaving(true);setError("");const f=new FormData(e.currentTarget);const val=(n:string)=>String(f.get(n)||"").trim();const payload={fullName:val("fullName"),phone:val("phone"),email:val("email"),method:val("method"),status:val("status"),sessionId:event.is_multi_session?val("sessionId")||null:null,notes:val("notes"),attended:f.get("attended")==="on",...(editor.type==="new"?{sendEmail:f.get("sendEmail")==="on"}:{})};try{const item=await savePayload(editor.type==="new"?`/api/admin/events/${event.id}/registrations`:`/api/admin/events/${event.id}/registrations/${editor.registration.id}`,editor.type==="new"?"POST":"PUT",payload);setRegistrations(cur=>editor.type==="new"?[...cur,item]:cur.map(r=>r.id===item.id?item:r));setEditor(null);router.refresh();}catch(c){setError(c instanceof Error?c.message:"未能儲存參加者");}finally{setSaving(false)}}
 async function resendEmail(r:RegistrationRecord){if(!r.email){setError("參加者未有提供電郵地址");return;}setSaving(true);setError("");try{const response=await fetch(`/api/admin/events/${event.id}/registrations/${r.id}/email`,{method:"POST"});const result=await response.json();if(!response.ok)throw new Error(result.error||"未能發送確認電郵");setRegistrations(cur=>cur.map(item=>item.id===r.id?{...item,email_sent:true,email_error:null}:item));alert(`確認電郵已發送至 ${r.email}`);}catch(c){setError(c instanceof Error?c.message:"未能發送確認電郵");}finally{setSaving(false)}}
 async function remove(r:RegistrationRecord){if(!confirm(`確定刪除「${r.full_name}」？`))return;const response=await fetch(`/api/admin/events/${event.id}/registrations/${r.id}`,{method:"DELETE"});const result=await response.json();if(!response.ok){setError(result.error||"未能刪除");return;}setRegistrations(cur=>cur.filter(x=>x.id!==r.id));router.refresh();}
 async function move(registrationId:string,sessionId:string){const r=registrations.find(x=>x.id===registrationId);if(!r||r.session_id===sessionId)return;setError("");try{const item=await savePayload(`/api/admin/events/${event.id}/registrations/${r.id}`,"PUT",{fullName:r.full_name,email:r.email||"",phone:r.phone,method:r.method,status:r.status,notes:r.notes||"",attended:Boolean(r.attended_at),sessionId});setRegistrations(cur=>cur.map(x=>x.id===item.id?item:x));router.refresh();}catch(c){setError(c instanceof Error?c.message:"未能移動參加者");}}
 function drop(e:DragEvent,sessionId:string){e.preventDefault();const id=e.dataTransfer.getData("text/registration-id")||dragId;if(id)void move(id,sessionId);setDragId(null)}
 async function importExcel(e:FormEvent<HTMLFormElement>){e.preventDefault();setImporting(true);setError("");setImportResult(null);const form=new FormData(e.currentTarget);try{const response=await fetch(`/api/admin/events/${event.id}/registrations/import`,{method:"POST",body:form});const result=await response.json();if(!response.ok&&response.status!==207)throw new Error(result.errors?.join("\n")||result.error||"未能匯入 Excel");setImportResult({importedCount:result.importedCount||0,failedCount:result.failedCount||0,emailsSent:result.emailsSent||0,failures:result.failures||[]});if(Array.isArray(result.registrations)&&result.registrations.length)setRegistrations(cur=>[...cur,...result.registrations]);router.refresh();}catch(c){setError(c instanceof Error?c.message:"未能匯入 Excel");}finally{setImporting(false)}}
 const editing=editor?.type==="edit"?editor.registration:null;
 return <><div className="registration-list-heading"><div><h2>參加者名單</h2><p>{event.is_multi_session?"拖動參加者卡片至其他時段；名額會即時重新核對。":"管理員可手動新增、修改及刪除參加者。"}</p></div><div className="registration-list-actions"><a className="button button-secondary button-small" href={`/api/admin/events/${event.id}/registrations/export`}><Download/>匯出 CSV</a><button className="button button-secondary button-small" onClick={()=>{setShowImport(true);setImportResult(null);setError("")}}><FileSpreadsheet/>Excel 批量輸入</button>{event.accepts_waitlist&&<button className="button button-secondary button-small" onClick={()=>setEditor({type:"new",defaultStatus:"waitlist"})}><Plus/>新增候補</button>}<button className="button button-primary button-small" onClick={()=>setEditor({type:"new",defaultStatus:"confirmed"})}><Plus/>新增參加者</button></div></div>{error&&!editor&&<div className="notice notice-error"><AlertCircle/>{error}</div>}
 <div className={event.is_multi_session?"session-registration-board":"registration-list-panel"}>{confirmedGroups.map(group=><section key={group.session?.id||"single"} className="session-registration-column" onDragOver={e=>e.preventDefault()} onDrop={e=>group.session&&drop(e,group.session.id)}><header><div><strong>{group.session?formatDateTime(group.session.start_at):event.title}</strong><span>{group.session?`${group.session.confirmed_count}/${group.session.capacity} 人`:`${event.confirmed_count}/${event.capacity} 人`}</span></div>{group.session&&<small>尚餘 {Math.max(0,group.session.capacity-group.session.confirmed_count)} 位</small>}</header><div className="session-participant-list">{group.items.map(r=><article key={r.id} className={`participant-card ${r.status}`} draggable={Boolean(group.session)} onDragStart={e=>{setDragId(r.id);e.dataTransfer.setData("text/registration-id",r.id)}}><GripVertical/><div><strong>{r.full_name}</strong><span>{r.phone}{r.email?` · ${r.email}`:""}</span><small>{statusLabels[r.status]} · {r.registration_no}</small></div><button className="icon-button" onClick={()=>setEditor({type:"edit",registration:r})}><Pencil/></button></article>)}{group.items.length===0&&<div className="empty-session-drop"><UsersRound/><span>拖動參加者到這裡</span></div>}</div></section>)}</div>
 {(event.accepts_waitlist||waitlistCount>0)&&<section className="admin-waitlist-section"><div className="registration-list-heading"><div><h2>候補名單</h2><p>共 {waitlistCount} 人。候補人數只在管理後台顯示，不會公開於前台。</p></div>{event.accepts_waitlist&&<button className="button button-secondary button-small" onClick={()=>setEditor({type:"new",defaultStatus:"waitlist"})}><Plus/>手動新增候補</button>}</div><div className={event.is_multi_session?"session-registration-board":"registration-list-panel"}>{waitlistGroups.map(group=><section key={`waitlist-${group.session?.id||"single"}`} className="session-registration-column waitlist-column"><header><div><strong>{group.session?formatDateTime(group.session.start_at):event.title}</strong><span>候補名單</span></div></header><div className="session-participant-list">{group.items.map(r=><article key={r.id} className="participant-card waitlist"><UsersRound/><div><strong>{r.full_name}</strong><span>{r.phone}{r.email?` · ${r.email}`:""}</span><small>候補 · {r.registration_no}</small></div><button className="icon-button" onClick={()=>setEditor({type:"edit",registration:r})}><Pencil/></button></article>)}{group.items.length===0&&<div className="empty-session-drop"><UsersRound/><span>暫未有候補</span></div>}</div></section>)}</div></section>}
 {showImport&&<div className="admin-modal-backdrop"><section className="admin-registration-modal excel-import-modal"><header><div><p>BULK IMPORT</p><h2>Excel 批量輸入參加者</h2></div><button className="icon-button" onClick={()=>setShowImport(false)}><X/></button></header><div className="excel-import-steps"><article><span>1</span><div><strong>下載指定格式</strong><p>範本已包括欄位說明；多時段活動另附可選日期及時段。</p><a className="button button-secondary button-small" href={`/api/admin/events/${event.id}/registrations/template`}><Download/>下載 Excel 範本</a></div></article><article><span>2</span><div><strong>填寫參加者資料</strong><p>請勿修改標題列。每次最多匯入 500 人，檔案不可超過 5MB。</p></div></article><article><span>3</span><div><strong>上傳並匯入</strong><p>系統會核對電話、電郵、狀態、時段及剩餘名額。</p></div></article></div><form onSubmit={importExcel} className="excel-import-form"><label className="excel-drop-field"><UploadCloud/><strong>選擇 .xlsx Excel 檔案</strong><span>只支援由本系統範本製作的 Excel</span><input type="file" name="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required/></label>{error&&<div className="notice notice-error excel-import-error"><AlertCircle/><pre>{error}</pre></div>}{importResult&&<div className={`excel-import-result ${importResult.failedCount?"partial":"success"}`}><CheckCircle2/><div><strong>已完成匯入</strong><p>成功 {importResult.importedCount} 人；失敗 {importResult.failedCount} 人；已發送確認電郵 {importResult.emailsSent} 封。</p>{importResult.failures.length>0&&<ul>{importResult.failures.map((item,index)=><li key={index}>{item}</li>)}</ul>}</div></div>}<footer className="admin-modal-actions"><button type="button" className="button button-secondary" onClick={()=>setShowImport(false)}>關閉</button><button className="button button-primary" disabled={importing}>{importing?<><LoaderCircle className="spin"/>匯入中…</>:<><FileSpreadsheet/>開始匯入</>}</button></footer></form></section></div>}
 {editor&&<div className="admin-modal-backdrop"><section className="admin-registration-modal"><header><div><p>PARTICIPANT</p><h2>{editor.type==="new"?(editor.defaultStatus==="waitlist"?"新增候補":"新增參加者"):"修改參加者"}</h2></div><button className="icon-button" onClick={()=>setEditor(null)}><X/></button></header><form onSubmit={submit}><div className="form-grid">{event.is_multi_session&&<label className="field field-full"><span>活動日期及時段 *</span><select name="sessionId" required defaultValue={editing?.session_id||sessions[0]?.id}>{sessions.map(s=><option value={s.id} key={s.id}>{formatDateTime(s.start_at)}（尚餘 {Math.max(0,s.capacity-s.confirmed_count)} 位）</option>)}</select></label>}<label className="field field-full"><span>姓名 *</span><input name="fullName" required defaultValue={editing?.full_name}/></label><label className="field"><span>電話 *</span><input name="phone" required defaultValue={editing?.phone}/></label><label className="field"><span>電郵（選填）</span><input name="email" type="email" defaultValue={editing?.email||""}/></label><label className="field"><span>狀態</span><select name="status" defaultValue={editing?.status||(editor?.type==="new"?editor.defaultStatus:"confirmed")||"confirmed"}><option value="confirmed">已確認</option><option value="waitlist">候補</option><option value="cancelled">已取消</option></select></label><label className="field"><span>報名方式</span><select name="method" defaultValue={editing?.method||event.registration_methods[0]}>{event.registration_methods.map(m=><option key={m} value={m}>{m==="online"?"網上":"親身"}</option>)}</select></label><label className="field field-full"><span>備註</span><textarea name="notes" defaultValue={editing?.notes||""}/></label></div><div className="admin-registration-options"><label><input type="checkbox" name="attended" defaultChecked={Boolean(editing?.attended_at)}/>已出席</label>{editor.type==="new"&&editor.defaultStatus!=="waitlist"&&<label><input type="checkbox" name="sendEmail"/>發送確認電郵</label>}</div>{error&&<div className="notice notice-error"><AlertCircle/>{error}</div>}<footer className="admin-modal-actions">{editing?.email&&editing.status==="confirmed"&&<button type="button" className="button button-secondary" disabled={saving} onClick={()=>void resendEmail(editing)}><MailCheck/>重新發送確認電郵</button>}{editing&&<button type="button" className="button button-danger" onClick={()=>void remove(editing)}><Trash2/>刪除</button>}<button type="button" className="button button-secondary" onClick={()=>setEditor(null)}>取消</button><button className="button button-primary" disabled={saving}>{saving?<><LoaderCircle className="spin"/>儲存中…</>:<><Save/>儲存</>}</button></footer></form></section></div>}</>;
}
