"use client";
import { useMemo, useState, type DragEvent, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { AlertCircle, Download, GripVertical, LoaderCircle, Pencil, Plus, Save, Trash2, UsersRound, X } from "lucide-react";
import type { EventRecord, RegistrationRecord, RegistrationStatus } from "@/lib/types";
import { formatDateTime } from "@/lib/format";

type Editor = { type:"new" } | { type:"edit"; registration:RegistrationRecord } | null;
const statusLabels:Record<RegistrationStatus,string>={confirmed:"已確認",waitlist:"候補",cancelled:"已取消"};
export function AdminRegistrationManager({event,initialRegistrations}:{event:EventRecord;initialRegistrations:RegistrationRecord[]}){
 const router=useRouter(); const [registrations,setRegistrations]=useState(initialRegistrations); const [editor,setEditor]=useState<Editor>(null); const [error,setError]=useState(""); const [saving,setSaving]=useState(false); const [dragId,setDragId]=useState<string|null>(null);
 const sessions=useMemo(()=>[...(event.sessions||[])].sort((a,b)=>a.start_at.localeCompare(b.start_at)),[event.sessions]);
 const groups=useMemo(()=>event.is_multi_session?sessions.map(s=>({session:s,items:registrations.filter(r=>r.session_id===s.id)})):[{session:null,items:registrations}],[event.is_multi_session,sessions,registrations]);
 async function savePayload(endpoint:string,method:string,payload:unknown){const response=await fetch(endpoint,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||"未能儲存參加者");return result as RegistrationRecord;}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editor)return;setSaving(true);setError("");const f=new FormData(e.currentTarget);const val=(n:string)=>String(f.get(n)||"").trim();const payload={fullName:val("fullName"),phone:val("phone"),email:val("email"),method:val("method"),status:val("status"),sessionId:event.is_multi_session?val("sessionId")||null:null,notes:val("notes"),attended:f.get("attended")==="on",...(editor.type==="new"?{sendEmail:f.get("sendEmail")==="on"}:{})};try{const item=await savePayload(editor.type==="new"?`/api/admin/events/${event.id}/registrations`:`/api/admin/events/${event.id}/registrations/${editor.registration.id}`,editor.type==="new"?"POST":"PUT",payload);setRegistrations(cur=>editor.type==="new"?[...cur,item]:cur.map(r=>r.id===item.id?item:r));setEditor(null);router.refresh();}catch(c){setError(c instanceof Error?c.message:"未能儲存參加者");}finally{setSaving(false)}}
 async function remove(r:RegistrationRecord){if(!confirm(`確定刪除「${r.full_name}」？`))return;const response=await fetch(`/api/admin/events/${event.id}/registrations/${r.id}`,{method:"DELETE"});const result=await response.json();if(!response.ok){setError(result.error||"未能刪除");return;}setRegistrations(cur=>cur.filter(x=>x.id!==r.id));router.refresh();}
 async function move(registrationId:string,sessionId:string){const r=registrations.find(x=>x.id===registrationId);if(!r||r.session_id===sessionId)return;setError("");try{const item=await savePayload(`/api/admin/events/${event.id}/registrations/${r.id}`,"PUT",{fullName:r.full_name,email:r.email||"",phone:r.phone,method:r.method,status:r.status,notes:r.notes||"",attended:Boolean(r.attended_at),sessionId});setRegistrations(cur=>cur.map(x=>x.id===item.id?item:x));router.refresh();}catch(c){setError(c instanceof Error?c.message:"未能移動參加者");}}
 function drop(e:DragEvent,sessionId:string){e.preventDefault();const id=e.dataTransfer.getData("text/registration-id")||dragId;if(id)void move(id,sessionId);setDragId(null)}
 const editing=editor?.type==="edit"?editor.registration:null;
 return <><div className="registration-list-heading"><div><h2>參加者名單</h2><p>{event.is_multi_session?"拖動參加者卡片至其他時段；名額會即時重新核對。":"管理員可手動新增、修改及刪除參加者。"}</p></div><div className="registration-list-actions"><a className="button button-secondary button-small" href={`/api/admin/events/${event.id}/registrations/export`}><Download/>匯出 CSV</a><button className="button button-primary button-small" onClick={()=>setEditor({type:"new"})}><Plus/>新增參加者</button></div></div>{error&&!editor&&<div className="notice notice-error"><AlertCircle/>{error}</div>}
 <div className={event.is_multi_session?"session-registration-board":"registration-list-panel"}>{groups.map(group=><section key={group.session?.id||"single"} className="session-registration-column" onDragOver={e=>e.preventDefault()} onDrop={e=>group.session&&drop(e,group.session.id)}><header><div><strong>{group.session?formatDateTime(group.session.start_at):event.title}</strong><span>{group.session?`${group.session.confirmed_count}/${group.session.capacity} 人`:`${event.confirmed_count}/${event.capacity} 人`}</span></div>{group.session&&<small>尚餘 {Math.max(0,group.session.capacity-group.session.confirmed_count)} 位</small>}</header><div className="session-participant-list">{group.items.map(r=><article key={r.id} className={`participant-card ${r.status}`} draggable={Boolean(group.session)} onDragStart={e=>{setDragId(r.id);e.dataTransfer.setData("text/registration-id",r.id)}}><GripVertical/><div><strong>{r.full_name}</strong><span>{r.phone}{r.email?` · ${r.email}`:""}</span><small>{statusLabels[r.status]} · {r.registration_no}</small></div><button className="icon-button" onClick={()=>setEditor({type:"edit",registration:r})}><Pencil/></button></article>)}{group.items.length===0&&<div className="empty-session-drop"><UsersRound/><span>拖動參加者到這裡</span></div>}</div></section>)}</div>
 {editor&&<div className="admin-modal-backdrop"><section className="admin-registration-modal"><header><div><p>PARTICIPANT</p><h2>{editor.type==="new"?"新增參加者":"修改參加者"}</h2></div><button className="icon-button" onClick={()=>setEditor(null)}><X/></button></header><form onSubmit={submit}><div className="form-grid">{event.is_multi_session&&<label className="field field-full"><span>活動日期及時段 *</span><select name="sessionId" required defaultValue={editing?.session_id||sessions[0]?.id}>{sessions.map(s=><option value={s.id} key={s.id}>{formatDateTime(s.start_at)}（尚餘 {Math.max(0,s.capacity-s.confirmed_count)} 位）</option>)}</select></label>}<label className="field field-full"><span>姓名 *</span><input name="fullName" required defaultValue={editing?.full_name}/></label><label className="field"><span>電話 *</span><input name="phone" required defaultValue={editing?.phone}/></label><label className="field"><span>電郵（選填）</span><input name="email" type="email" defaultValue={editing?.email||""}/></label><label className="field"><span>狀態</span><select name="status" defaultValue={editing?.status||"confirmed"}><option value="confirmed">已確認</option><option value="waitlist">候補</option><option value="cancelled">已取消</option></select></label><label className="field"><span>報名方式</span><select name="method" defaultValue={editing?.method||event.registration_methods[0]}>{event.registration_methods.map(m=><option key={m} value={m}>{m==="online"?"網上":"親身"}</option>)}</select></label><label className="field field-full"><span>備註</span><textarea name="notes" defaultValue={editing?.notes||""}/></label></div><div className="admin-registration-options"><label><input type="checkbox" name="attended" defaultChecked={Boolean(editing?.attended_at)}/>已出席</label>{editor.type==="new"&&<label><input type="checkbox" name="sendEmail"/>發送確認電郵</label>}</div>{error&&<div className="notice notice-error"><AlertCircle/>{error}</div>}<footer className="admin-modal-actions">{editing&&<button type="button" className="button button-danger" onClick={()=>void remove(editing)}><Trash2/>刪除</button>}<button type="button" className="button button-secondary" onClick={()=>setEditor(null)}>取消</button><button className="button button-primary" disabled={saving}>{saving?<><LoaderCircle className="spin"/>儲存中…</>:<><Save/>儲存</>}</button></footer></form></section></div>}</>;
}
